/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Furniture")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class Furniture : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "4fc462712576fa7428bac71d410e286c";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_objSittable = default;
        [SerializeField] public UnityEngine.GameObject m_objFurniture = default;
        [SerializeField] public UnityEngine.GameObject m_fx_circleAvailable = default;
        [SerializeField] public UnityEngine.GameObject m_fx_circleOccupied = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_objSittable),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_objFurniture),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_fx_circleAvailable),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_fx_circleOccupied),
            };
        }
    }
}

#endif
