/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GameManager")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class GameManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "19bde4c2aab77794fa119fe23c48d535";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader m_music = default;
        [SerializeField] public UnityEngine.GameObject m_areaSpectator = default;
        [SerializeField] public UnityEngine.GameObject m_areaGame = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_music),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_areaSpectator),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_areaGame),
            };
        }
    }
}

#endif
