/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/RoundManager")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class RoundManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "f1756e156cce781478fcf207ea5ec630";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_furniture1 = default;
        [SerializeField] public UnityEngine.GameObject m_furniture2 = default;
        [SerializeField] public UnityEngine.GameObject m_furniture3 = default;
        [SerializeField] public UnityEngine.GameObject m_furniture4 = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_furniture1),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_furniture2),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_furniture3),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_furniture4),
            };
        }
    }
}

#endif
