/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIInstructions")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class UIInstructions : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b297e9b4f25309b448fb4cf030449bab";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader m_sfx_uiOpen = default;
        [SerializeField] public Highrise.AudioShader m_sfx_uiClose = default;
        [SerializeField] public Highrise.AudioShader m_sfx_uiNextPage = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
                CreateSerializedProperty(_script.GetPropertyAt(5), null),
                CreateSerializedProperty(_script.GetPropertyAt(6), null),
                CreateSerializedProperty(_script.GetPropertyAt(7), null),
                CreateSerializedProperty(_script.GetPropertyAt(8), null),
                CreateSerializedProperty(_script.GetPropertyAt(9), null),
                CreateSerializedProperty(_script.GetPropertyAt(10), null),
                CreateSerializedProperty(_script.GetPropertyAt(11), null),
                CreateSerializedProperty(_script.GetPropertyAt(12), null),
                CreateSerializedProperty(_script.GetPropertyAt(13), null),
                CreateSerializedProperty(_script.GetPropertyAt(14), null),
                CreateSerializedProperty(_script.GetPropertyAt(15), null),
                CreateSerializedProperty(_script.GetPropertyAt(16), null),
                CreateSerializedProperty(_script.GetPropertyAt(17), null),
                CreateSerializedProperty(_script.GetPropertyAt(18), null),
                CreateSerializedProperty(_script.GetPropertyAt(19), null),
                CreateSerializedProperty(_script.GetPropertyAt(20), null),
                CreateSerializedProperty(_script.GetPropertyAt(21), null),
                CreateSerializedProperty(_script.GetPropertyAt(22), null),
                CreateSerializedProperty(_script.GetPropertyAt(23), null),
                CreateSerializedProperty(_script.GetPropertyAt(24), null),
                CreateSerializedProperty(_script.GetPropertyAt(25), m_sfx_uiOpen),
                CreateSerializedProperty(_script.GetPropertyAt(26), m_sfx_uiClose),
                CreateSerializedProperty(_script.GetPropertyAt(27), m_sfx_uiNextPage),
            };
        }
    }
}

#endif
